// Generated by CoffeeScript 1.6.3
(function() {
  var async, io, kills, request;

  async = require('async');

  request = require('request');

  io = require('socket.io').listen(9001);

  kills = io.of('/kills');

  setInterval(function() {
    var killmails;
    killmails = [];
    console.log('Running the update');
    return async.parallel([
      function(cb) {
        return request({
          url: 'http://api.whelp.gg/alliance/99002172/losses',
          json: true
        }, function(error, res, body) {
          if (!error && res.statusCode === 200) {
            return killmails.concat(body['kills']);
          }
        });
      }, function(cb) {
        return request({
          url: 'http://api.whelp.gg/alliance/99002172',
          json: true
        }, function(error, res, body) {
          if (!error && res.statusCode === 200) {
            return killmails.concat(body['kills']);
          }
        });
      }
    ], function(err, killmails) {
      console.log('Updated');
      return kills.emit('update', killmails);
    });
  }, 10000);

}).call(this);
